### ISSUE TITLE
RX/TX Belegung

### ISSUE THREAD

**Issue by bigmacblau** [d4rken/jbd-bms-mqtt#1]
Hallo und Danke für Deine tolle Arbeit.  Das JBD BMS AP21S001 scheint ja etwas anders im Protokoll bzw. Checksumme zu sein als die anderen JBD BMS, deshalb bin ich auf Deinen Ansatz gestoßen. (Bei anderen Ansätzen bekomme ich keine Basisdaten) Sehe ich das richtig das Du zur Kommunikation D1 und D2 am ESP abfragt und nicht RX/TX ?  Ich möchte versuchen den ESP am BLE Anschluss des BMS anzuschließen. Könnte das gehen?
Danke Dir
Gruß Wolfgang
Hello and thank you for your great work. The JBD BMS AP21S001 seems to be a bit different in the protocol or checksum than the other JBD BMS, that's why I came across your approach. (I don't get any basic data with other approaches) Do I see that correctly that you query D1 and D2 on the ESP for communication and not RX/TX? I want to try to connect the ESP to the BLE port of the BMS. Could that work?
Thank you
Greetings Wolfgang

**Comment by d4rken** [comment]
Ich spreche Deutsch aber wenn die Texte auf Englisch sind hilft es mehr Leuten :slightly_smiling_face: .

> Hello and thank you for your great work. The JBD BMS AP21S001 seems to be a bit different in the protocol or checksum than the other JBD BMS, that's why I came across your approach. (I don't get any basic data with other approaches)

Yeah the message length is different. I got the idea from here:
https://github.com/rahmaevao/JbdBms/issues/13

I then just let it output raw data and counted the actual message length based on that. It was 45 bytes:
https://github.com/d4rken/jbd-bms-mqtt/commit/3709450518f8b1a7ecf4683a00ff1e1071a33961#diff-3fa9bd67bcda8be62c95b6ec99f27fd66065b1c94a7a28f4b44ec4055f0ecf1eR17

Also this BMS has an extra temp sensor that I added.

> Do I see that correctly that you query D1 and D2 on the ESP for communication and not RX/TX?

Yes: 
https://github.com/d4rken/jbd-bms-mqtt/blob/ecfc9e979d853ba64b914ffccd65edd809f98042/src/main.cpp#L21

I'm not really sure if it makes a difference? I don't remember why I picked these ports.
Theoretically all of the GPIO pins are equal?
https://edistechlab.com/esp8266-wemos-d1-mini-pin-out

Maybe because of the RS485 module?

> I want to try to connect the ESP to the BLE port of the BMS. Could that work?

I think that works and then you might not need the RS485 module. The BLE port is just straight serial communication. But you'll have to try it :shrug:.

I didn't want to do that because then it's either Bluetooth or Arduino, now I can keep using both :smile:.

**Comment by bigmacblau** [comment]
Thank you for your explanation. I connected it and it works !!!!!!!
Only the temperature shows -270 for both sensors? but I don't care. Thank you again
greeting
wolfgang

**Comment by bigmacblau** [comment]
Hello, it's me again. I have noticed the following problem during operation. The ESP transmits data via MQTT to IObroker in intervals of approx. 25 sec. But after 1 hour at the latest, the data is no longer up to date. The same old data are always transmitted. Do you have an idea what could be the cause.
Greetings
Wolfgang

**Comment by d4rken** [comment]
Is old data being transmitted, or is nothing being transmitted?

If old data is being transmitted, you'd have to check the debug output of the arduino if there are errors.
I didn't have any issues with this.

I had issues where no data was being transmitted due to bad WiFi reception. Though the code has some retry mechanisms, in the end I added a repeater closer to my setup.

**Comment by bigmacblau** [comment]
so it looks like no more data is being transmitted. The WLan login is correct. I have checked this in the router and IOBroker. Only switching off the power brings back data. Can I run a logger to find the error?

**Comment by d4rken** [comment]
Wifi issues are common with Arduinos, you'll have to debug this.
